### ISSUE TITLE
Unable to build non-Android java project

### ISSUE THREAD

**Issue by Monroe1701** [passsy/gradle-gitVersioner-plugin#15]
I have a multiproject gradle project:
"root"
    |- "app1"
    |- "app2"

gradle.build of "root" looks like this:
```groovy
buildscript {
    dependencies {
       // GitVersioner Plugin
        classpath 'com.pascalwelsch.gitversioner:gitversioner:0.4.1'
    }
}
apply plugin: 'com.pascalwelsch.gitversioner'

    gitVersioner {
        baseBranch 'develop'
        addSnapshot false
        addLocalChangesDetails false

        println versionName()
    }
```

Now I want to use the version name in app1 and app2 or even in root for that matter, but gitVersioner.versionName is not available.
Each app has it's own version set and the version name from gitVersioner should be appended to both.

I'm not a gradle expert, so it might be that i'm missing something or this plugin is only for Android development.

**Comment by passsy** [comment]
> but gitVersioner.versionName is not available.

What happens if you try to use it? You won't get auto-completion. It's a property which is only available at runtime. Or do you get an error?

This plugin is pure gradle and works for all gradle projects including Android, not exclusive android.

**Comment by Monroe1701** [comment]
In the _gradle.build_ of "app1" I have 
```
   version = '7.3.0.0-SNAPSHOT' + gitVersioner.versionName
```
I have nothing else related to gitVersioner configured in that file.

The error message I get is:
```
Could not get unknown property 'gitVersioner' for root project 'service-fahrtverlauf' of type org.gradle.api.Project.
```

**Comment by Monroe1701** [comment]
Thank you very much. It works. Don't know what it was, but reorganising the project helped.
