### ISSUE TITLE
Branchnames with prefixes other than "feature/" break the build

### ISSUE THREAD

**Issue by tobias-neubert** [passsy/gradle-gitVersioner-plugin#16]
The version name for a feature branch like this "feature/XYZ-566-something" is correctly converted into the version name "-XYZ-566-something". And with that version name the name of the resulting .jar file is correct.

But if I use a different prefix, "bugfix" for example, the prefix will not be removed from the version name leading to a completely broken .jar name of my resulting artifact.

I would like to have the same behaviour for any prefix, simply remove it.

To reproduce:

    Create a simple java library project
    Create a branch named "bugfix/Something"
    Build the jar file

**Comment by tobias-neubert** [comment]
I added a very tiny PR that solves this issue. At least, the way I want it to be solved :-)

**Comment by passsy** [comment]
Fixed
