### ISSUE TITLE
Host on Maven Central

### ISSUE THREAD

**Issue by svenjacobs** [passsy/gradle-gitVersioner-plugin#22]
Since JCenter is [sunsetting](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) on May 1st, please host the plugin on Maven Central. [Sonatype OSSRH](https://central.sonatype.org/pages/ossrh-guide.html) might be of help.

**Comment by svenjacobs** [comment]
Closing as JCenter remains read-only "indefinitely". However this also means that no updates of this plugin can be deployed to JCenter anymore.

**Comment by passsy** [comment]
I should publish it to the github repo as well

**Comment by Tejpbit** [comment]
We got around this by using
```
buildscript {
    repositories {
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.github.passsy:gradle-gitVersioner-plugin:0.5.0'
    }
}
```

**Comment by LluisFelip** [comment]
> We got around this by using
> 
```
buildscript {
     repositories {
         maven { url 'https://jitpack.io' }
     }
     dependencies {
         classpath 'com.github.passsy:gradle-gitVersioner-plugin:0.5.0'
     }
 }
```

Thanks for this!
