### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [passsy/gradle-gitVersioner-plugin#6]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by passsy** [comment]
Not going to use is regardless of the functionality.

Your shameless spam is the worst advertising I've ever seen for a library @oleksiyp  
<img width="423" alt="screen shot 2017-12-25 at 12 18 08" src="https://user-images.githubusercontent.com/1096485/34338906-bd093ece-e96d-11e7-961d-a8673cff74a3.png">
