### ISSUE TITLE
The git Version task gets stuck in windows

### ISSUE THREAD

**Issue by sergio11** [passsy/gradle-gitVersioner-plugin#8]
Hi,

I love this plugin, I've been using it for a long time. Now, I have a problem when building my project on a PC with windows 10 the task gitVersion is blocked and the process does not end.

I have tried both with the old script and with this and in both cases the construction of the project never ends

![captura](https://user-images.githubusercontent.com/6996211/38878704-dc6d5668-4261-11e8-90f0-cac6d3c094bc.PNG)

![captura_2](https://user-images.githubusercontent.com/6996211/38878736-f2b30206-4261-11e8-83a8-fb76726391a0.PNG)

Could you tell me what the problem is?

regards

**Comment by passsy** [comment]
Wrong repo. You are using the [script](https://github.com/passsy/gradle-GitVersioner) version which is outdated and not maintained for a long time.

Please upgrade to the plugin (this repo here) and make sure you use version `0.3.1`

See [install](https://github.com/passsy/gradle-gitVersioner-plugin#install) in the readme.

**Comment by passsy** [comment]
Oh that's bad. Please help me to narrow down this problem:

1. Are there any useful information when you run `./gradlew assemble --info` or `--debug`?
2. Does it hang if you remove `gitVersioner.versionCode` or `gitVersioner.versionName` or both from your gradle script?
3. Are you able to run `./gradlew gitVersion --info` after you removed `versionCode` and `versionName` from your gradle script?

**Comment by sergio11** [comment]
Hello,

I have done everything you say, I have deleted `versionCode `and `versionName `of my gradle script and it is blocked in all cases. I give you an example of the output of the command:

`./gradlew assemble --info`

![captura_1](https://user-images.githubusercontent.com/6996211/38924121-5c66d660-42fc-11e8-9bbc-0802f7a1a3dd.PNG)

I do not know what else to try, in all cases it is blocked.


Thank you!!!

**Comment by passsy** [comment]
Does it work when you remove `apply plugin: 'com.pascalwelsch.gitversioner'`?

**Comment by sergio11** [comment]
I use version 4.1. If I delete that line, the project compiles. Thank you!!

**Comment by passsy** [comment]
Can you verify it works on a new project? It could be a problem of running it on windows at all :/

**Comment by sergio11** [comment]
I've tried it on three different projects and the same thing happens

**Comment by DagobertDokate** [comment]
Same problem here =(. Used it for some time. But after while it's not working reliable.
It works better when there are no uncommited files. When there are any changes, it is not working.
Windows 10. AS 3.1.4.

**Comment by DagobertDokate** [comment]
Is there any new advice? =)

**Comment by passsy** [comment]
can you please try the command line tool [git-revision](https://github.com/passsy/git-revision/releases)? It will replace the core logic in the project soon. Would be good to know if it's working.

Also what's your git version? I found out at least git `2.2.0` is required.

**Comment by staceybellerose** [comment]
I've run into the same problem, first with the deprecated script version, and again with this plugin. I traced it to the `git status` line blocking due to a filled buffer. This only happens when `git status` output is large, such as when there are numerous uncommitted files.

The fix is to read result.inputStream before the `when (result.exitValue()) {` line. I don't know enough Kotlin to fix this plugin, but I have fixed my fork of the old script version, which now works again.

**Comment by passsy** [comment]
Thanks @staceybellerose for the hint. I'm finally able to reproduce it! I'm on it

**Comment by DagobertDokate** [comment]
Any news for us? =)

**Comment by passsy** [comment]
A fix is released in `0.4.0`

**Comment by DagobertDokate** [comment]
How can I send you a beer? =)

**Comment by passsy** [comment]
@DagobertDokate now you can https://github.com/users/passsy/sponsorship
